version: "3.9"
services:
  ariel:
    tty: true
    container_name: ariel
    build: ..
    restart: always
    env_file:
      - "../src/.env.development"
      - "../src/.env.development.local"
      - "../prisma/.env.production.local"
    image: 'artiefuzzz/ariel:latest'
    networks:
      - ariel
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - ariel
    volumes:
      - './postgres:/var/lib/postgresql/data'

networks:
  ariel:
