version: "3.9"
services:
  ariel:
    tty: true
    container_name: ariel
    build: ..
    restart: always
    env_file:
      - "../src/.env.development"
      - "../src/.env.development.local"
      - "../prisma/.env.production.local"
    image: 'artiefuzzz/ariel:latest'
    networks:
      - ariel
    depends_on:
      - postgres
      - influx
      - redis
    logging:
      options:
        max-size: 1g
        max-file: '3'
  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - ariel
    volumes:
      - './postgres:/var/lib/postgresql/data'
  influx:
    image: influxdb:2.1-alpine
    command: 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt'
    container_name: influx
    restart: always
    ports:
      - 8285:8086
    networks:
      - ariel
    volumes:
      - './influx-data:/var/lib/influxdb2'

volumes:
  postgres:
    external: true
  influx-data:
    external: true

networks:
  ariel:
