version: "3.9"
services:
  ariel:
    container_name: ariel
    build: ..
    restart: always
    env_file:
      - "../src/.env.development"
      - "../src/.env.development.local"
    image: 'artiefuzzz/ariel:latest'
