name: "CD"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/CD.yml"
      - "package.json"

jobs:
  PushImage_Ariel:
    name: Build and Push Image to Ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push Ariel Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          context: .
          tags: |
            ghcr.io/astrieldivision/ariel:latest
            artiefuzzz/ariel:latest
            artiefuzzz/ariel:${{ github.sha }}
