name: Continuous Delivery

on:
  push:
    branches: [main]
  schedule:
    - cron: "* */23 * * *"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Namespace
        uses: okteto/namespace@master
        with:
          namespace: artiefuzzz
      - name: Configuration
        run: echo -n "${{ secrets.CONFIG }}" | base64 -d > config/main.json
      - name: Deploy Stack
        uses: okteto/deploy-stack@master
        with:
          build: true
