name: Continuous Delivery

on:
  push:
    branches: [main, starlight]
  schedule:
    - cron: "* * */23 * *"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Namespace
        uses: okteto/namespace@master
        with:
          namespace: artiefuzzz
      - name: Configuration
        if: github.ref == 'refs/heads/main'
        run: echo -n "${{ secrets.CONFIG }}" | base64 -d > config/main.json
      - name: Configuration
        if: github.ref == 'refs/heads/starlight'
        run: echo -n "${{ secrets.DEVCONFIG }}" | base64 -d > config/main.json
      - name: Deploy Stack (Nightly / starlight)
        if: github.ref == 'refs/heads/starlight'
        uses: okteto/deploy-stack@master
        with:
          name: Starlight
          build: true
      - name: Deploy Stack (Production / main)
        if: github.ref == 'refs/heads/main'
        uses: okteto/deploy-stack@master
        with:
          name: Ariel
          build: true
